### ISSUE TITLE
libOpenCvNative.so should be put into android external storage

### ISSUE THREAD

**Issue by KokeCacao** [OpenFTC/OpenCV-Repackaged#1]
In readme.md, it says that `libOpenCvNative.so` should be put in android internal storage. But it does not make sense since the internal storage of an app is hidden for the users. The only thing we can access from the file system is an app's external storage.

Accured: putting `libOpenCvNative.so` in internal storage

Expected: putting `libOpenCvNative.so` in external storage

ref: https://stackoverflow.com/questions/5092591/what-are-the-differences-among-internal-storage-external-storage-sd-card-and-r

**Comment by Windwoes** [comment]
By internal storage, I meant internal to the phone as opposed to external to the phone (I.e. SD card)

**Comment by KokeCacao** [comment]
> By internal storage, I meant internal to the phone as opposed to external to the phone (I.e. SD card)

Thanks. It will be good to add clarification to prevent confusion.
