### ISSUE TITLE
Manifest file has old opencv version info

### ISSUE THREAD

**Issue by shelbyRobots** [OpenFTC/OpenCV-Repackaged#10]
The AndroidManifest.xml file has old (4.1.0) opencv version info.
This can be corrected by removing the following lines from the manifest:
```
android:versionCode="4100"
android:versionName="4.1.0">
```      
and adding the definitions to the build.gradle before the android section:
```
def openCVersionName = "4.5.3"
def openCVersionCode = ((4 * 100 + 5) * 100 + 3) * 10 + 0
```

and the reference on those in the android.defaultConfig section:
```
versionCode openCVersionCode
versionName openCVersionName
```

The compileOnly reference to RobotCore should also be updated to 7.0.

Finally, it may be possible to use the annotation org.firstinspires.ftc.ftccommon.external.OnCreate on the loadNativeLibOnStartRobot method as opposed to the opModeRegistrar.  Not sure it is a huge difference, but may save some attempted reloads.

**Comment by Windwoes** [comment]
Thanks for pointing this out, I'll fix it for the next release
