### ISSUE TITLE
missing md5.txt files

### ISSUE THREAD

**Issue by AlexD70** [OpenFTC/OpenCV-Repackaged#11]
Md5 signatures are found on libs in /doc, but there are no md5.txt files in this project. They'd be useful to check for file corruption.

**Comment by Windwoes** [comment]
Well, you will get a pop-up if the MD5 doesn't match. Are you saying useful to check on the computer before transferring to the Control Hub?

**Comment by AlexD70** [comment]
Yeah, exactly. I wanted to check it the second time to make sure it isn't corrupted before uploading it to the RS.

**Comment by Windwoes** [comment]
Since v1.5.3, the native library is bundled instead of being loaded dynamically
