### ISSUE TITLE
Cannot add libOpenCvNative.so to control hub

### ISSUE THREAD

**Issue by Alexejhero** [OpenFTC/OpenCV-Repackaged#3]
The control hub has a read-only storage when connected to a computer via TypeC-USB, so files cannot be added to the `FIRST` folder.

**Comment by Windwoes** [comment]
That's not right, multiple people have been able to copy it to a Control Hub. It must be something specific with your configuration.

**Comment by Alexejhero** [comment]
I am connecting my control hub to my computer via a Type C / USB cable, it shows up in the `Devices and Drives` menu, and when I open it, a `Local shared storage` drive shows up with 12 GB of storage.

**Comment by Windwoes** [comment]
Are you on a Mac?

**Comment by Alexejhero** [comment]
Nope. Windows

**Comment by Windwoes** [comment]
Try using ADB:

```
adb push /path/to/libOpenCvNative.so /sdcard/FIRST/
```

By the way, I'm assuming you're using EasyOpenCV right? If so make sure you're using v1.3.1 or higher.

**Comment by Alexejhero** [comment]
Thanks. This worked
