### ISSUE TITLE
libOpenCvNative.so MD5 error

### ISSUE THREAD

**Issue by shiveshk72** [OpenFTC/OpenCV-Repackaged#4]
We are trying to use EasyOpenCV on a Moto G5 Plus running Android 7.0 . The libOpenCvNative.so file was copied using the ADB PUSH command to the /sdcard/FIRST folder. On staring the Robot Controller app we are getting the following error - " libOpenCvNative.so is corrupted - libOpenCvNative.so is present in the FIRST on the internal storage. However, the MD5 checksum, does not match what is expected. Any OpenCV-enabled OpModes will likely crash. Delete and re-download the file."

Running the following command using adb shell -
md5sum  libOpenCvNative.so
returns 
07a377983266cb64bd649bb233452970  libOpenCvNative.so

Any hints to what may be causing this ?

**Comment by Windwoes** [comment]
Well, the expected checksum is `83995833bd64b46a940e5eda8dafd620`.

If you're on Windows, can you use Microsoft's [FCIV tool](https://support.microsoft.com/en-us/help/841290) to check the MD5 of your downloaded copy?

If you're on a Mac, you can check the MD5 with `md5 /path/to/file` and if you're on Linux you can check it with `md5sum /path/to/file`

**Comment by shiveshk72** [comment]
Appreciate your quick response. I downloaded the tool and the output is as follows -

C:\FTC>fciv libOpenCvNative.so
//
// File Checksum Integrity Verifier version 2.05.
//
c6449394819da6fb77a408d8b8f3e668 libopencvnative.so
________________________________

**Comment by shiveshk72** [comment]
Ok. I re-downloaded the file using Microsoft Edge and the MD5 nos. match up as expected. Not sure how the save with Chrome was messing this up. Thanks for sharing the expected MD5.
