### ISSUE TITLE
Why are shared objects not packaged with the AAR?

### ISSUE THREAD

**Issue by pietroglyph** [OpenFTC/OpenCV-Repackaged#5]
Right now you instruct users to copy libOpenCvNative.so to a specific directory on the device and then you load the shared object from that specific path via `System.load`. This adds an extra step to the setup process, and I was wondering if there was any reason you don't place the shared object under `src/main/jniLibs/{ABI TRIPLE}/` where it will be automatically included in the AAR?

If there's no reason that this isn't being done then I'll go ahead and make a PR that packages the shared objects in this manner.

**Comment by Windwoes** [comment]
Actually, extra work was done *specifically* in order to be able to load it from external storage instead of packaging it with the artifact in order to prevent the RC APK from being bloated another 10MB, which can have a significant effect on wireless ADB deploy times.
