### ISSUE TITLE
64 bit native library?

### ISSUE THREAD

**Issue by enterlight** [OpenFTC/OpenCV-Repackaged#6]
When I start the Robot Controller, I get 
`Could not load OpenCV native library because app is running in 64-bit mode.  Please remove the arm64-v8a entries from build.common.gradle`
When I remove the arm64-v8a entries it works fine.  Just wondering if there is a 64 bit version of this library somewhere?

**Comment by Windwoes** [comment]
Yes, there is a 64-bit version - it's just the stock OpenCV Android SDK's precompiled native library - but at the moment I do not have plans to support that in OpenCV-Repackaged. It would make the dynamic native library loading code messier, and be another file the user would need to copy onto the device without any significant performance benefit as far as I'm aware. (Although if you can provide evidence to the contrary, I might be willing to reconsider).

**Comment by enterlight** [comment]
Thanks for your reply.
