### ISSUE TITLE
Requesting Update to OpenCV 4.5.3

### ISSUE THREAD

**Issue by IronReignRobotics** [OpenFTC/OpenCV-Repackaged#7]

**Comment by Windwoes** [comment]
Any specific thing you're looking to gain from a newer version? Not all improvements apply to the Android build.

**Comment by IronReignRobotics** [comment]
We are going for obstacle detection using intel realsense cameras. depth frames can be processed to remove ground point so that obstacles like other robots can be detected and avoided. Something similar to this:
http://www.sayef.tech/post/ground-detection-and-removal-from-point-clouds/
OpenCV 4.5 has an update to RANSAC that might perform well enough on control hub hardware:
https://opencv.org/evaluating-opencvs-new-ransacs/

**Comment by Windwoes** [comment]
Hmm, I am looking into this, but when I locally test 4.5.3, I am getting a dynamic linker error at runtime:

```
dlopen failed: library "libc++_shared.so" not found
```

**Comment by Windwoes** [comment]
Okay, managed to get past that by using a dummy target to have gradle pull that in.

If you add this maven staging repo:

```groovy
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/orgopenftc-1008/'}
}
```

You should be able to give my test build for 4.5.3 a try by doing the following:

```groovy
dependencies {
    implementation ('org.openftc:easyopencv:1.4.4') {
        exclude group: "org.openftc", module: "opencv-repackaged"
    }
    implementation 'org.openftc:opencv-repackaged:5.4.3-B'
}
```

Edit: whoops, I typoed the version number when I uploaded to the staging repo, (5.4.3 instead of 4.5.3). Doesn't really affect anything, I'll fix that before releasing.

**Comment by Windwoes** [comment]
Here's the updated native library.

[libOpenCvAndroid543.zip](https://github.com/OpenFTC/OpenCV-Repackaged/files/7110305/libOpenCvAndroid543.zip)

**Comment by IronReignRobotics** [comment]
Sweet - It Works!!!

Do you want me to close it now or once you release it?

**Comment by Windwoes** [comment]
Once I release it. Does the new version provide the improvements you were hoping for?

**Comment by IronReignRobotics** [comment]
It does. Not that we've been able to implement yet, but it has the
ransac/usac improvements introduced in 4.5.0. Thank you!

**Comment by Windwoes** [comment]
EOCV v1.5.0 is now live and uses OpenCV v4.5.3
