### ISSUE TITLE
OpenCV contrib modules (ArUco)

### ISSUE THREAD

**Issue by blueberrymuffin3** [OpenFTC/OpenCV-Repackaged#8]
Our team is interested in using code from opencv-contrib modules, specifically org.opencv.aruco. Is there anyway to do this while using EasyOpenCV and OpenCV-Reapackaged?

**Comment by Windwoes** [comment]
You would need to rebuild the OpenCV Android SDK from source with the extra features enabled, and when including EasyOpenCV, you would need to exclude the transitive dependency on OpenCV-Repackaged and instead include a dependency on your rebuilt versions.

Sidenote, I am considering offering a plug-n-play AprilTag add-on that can be fed frames through OpenCV.

**Comment by Windwoes** [comment]
> Sidenote, I am considering offering a plug-n-play AprilTag add-on that can be fed frames through OpenCV.

https://github.com/OpenFTC/EOCV-AprilTag-Plugin :))
